## 04. 반드시 알아야 하는 파이토치 스킬

### 4.1 텐서
텐서(Tensor) : 데이터를 표현하는 단위  

#### 4.1.1 Scalar
상숫값. 즉, 하나의 값을 표현할 때 1개의 수치로 표현한 것.  

In [1]:
import torch

/home/nyongja/anaconda3/envs/pytorch_study/lib/python3.7/site-packages/torch/package/_mock_zipreader.py:17: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448224956/work/torch/csrc/utils/tensor_numpy.cpp:67.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}


In [2]:
scalar1 = torch.tensor([1.])
print(scalar1)

tensor([1.])


In [3]:
scalar2 = torch.tensor([3.])
print(scalar2)

tensor([3.])


스칼라 값 사칙연산하기

In [4]:
add_scalar = scalar1 + scalar2
print(add_scalar)

tensor([4.])


In [5]:
sub_scalar = scalar1 - scalar2
print(sub_scalar)

tensor([-2.])


In [6]:
mul_scalar = scalar1 * scalar2
print(mul_scalar)

tensor([3.])


In [7]:
div_scalar = scalar1 / scalar2
print(div_scalar)

tensor([0.3333])


torch 모듈에 내장된 메서드를 이용해 계산도 가능

In [8]:
torch.add(scalar1, scalar2)

tensor([4.])

In [9]:
torch.sub(scalar1, scalar2)

tensor([-2.])

In [10]:
torch.mul(scalar1, scalar2)

tensor([3.])

In [11]:
torch.div(scalar1, scalar2)

tensor([0.3333])

#### 4.1.2 Vector
하나의 값을 표현할 때 2개 이상의 수치로 표현한 것. 

In [12]:
vector1 = torch.tensor([1., 2., 3.])
print(vector1)

tensor([1., 2., 3.])


In [13]:
vector2 = torch.tensor([4., 5., 6.])
print(vector2)

tensor([4., 5., 6.])


벡터 값 사칙연산 수행하기.  
스칼라 사칙연산과 동일한 방식.

In [14]:
add_vector = vector1 + vector2
print(add_vector)

tensor([5., 7., 9.])


In [15]:
sub_vector = vector1 - vector2
print(sub_vector)

tensor([-3., -3., -3.])


In [16]:
mul_vector = vector1 * vector2
print(mul_vector)

tensor([ 4., 10., 18.])


In [17]:
div_vector = vector1 / vector2
print(div_vector)

tensor([0.2500, 0.4000, 0.5000])


In [18]:
torch.add(vector1, vector2)

tensor([5., 7., 9.])

In [19]:
torch.sub(vector1, vector2)

tensor([-3., -3., -3.])

In [20]:
torch.mul(vector1, vector2)

tensor([ 4., 10., 18.])

In [21]:
torch.div(vector1, vector2)

tensor([0.2500, 0.4000, 0.5000])

#### 4.1.3 행렬
행렬은 2개 이상의 벡터 값을 통합해 구성된 값.  
벡터 값 간 연산 속도를 빠르게 진행할 수 있는 선형 대수의 기본 단위

In [22]:
matrix1 = torch.tensor([[1., 2.], [3., 4.]])
print(matrix1)

tensor([[1., 2.],
        [3., 4.]])


In [23]:
matrix2 = torch.tensor([[5., 6.], [7., 8.]])
print(matrix2)

tensor([[5., 6.],
        [7., 8.]])


행렬 값 간의 사칙연산을 수행.

In [24]:
sum_matrix = matrix1 + matrix2
print(sum_matrix)

tensor([[ 6.,  8.],
        [10., 12.]])


In [25]:
sub_matrix = matrix1 - matrix2
print(sub_matrix)

tensor([[-4., -4.],
        [-4., -4.]])


In [26]:
mul_matrix = matrix1 * matrix2
print(mul_matrix)

tensor([[ 5., 12.],
        [21., 32.]])


In [27]:
div_matrix = matrix1 / matrix2
print(div_matrix)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [28]:
torch.add(matrix1, matrix2)

tensor([[ 6.,  8.],
        [10., 12.]])

In [29]:
torch.sub(matrix1, matrix2)

tensor([[-4., -4.],
        [-4., -4.]])

In [30]:
torch.mul(matrix1, matrix2)

tensor([[ 5., 12.],
        [21., 32.]])

In [31]:
torch.div(matrix1, matrix2)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

In [32]:
torch.matmul(matrix1, matrix2)

tensor([[19., 22.],
        [43., 50.]])

#### 4.1.4 텐서
행렬을 2차원의 배열이라 표현할 수 있다면, 텐서는 2차원 이상의 배열이라 표현할 수 있음.  
텐서 내 행렬 단위의 인덱스 간, 행렬 내 인덱스 간 원소끼리 게산되며 행렬 곱은 텐서 내 같은 행렬 단위의 인덱스 간에 계산 됨.

In [33]:
tensor1 = torch.tensor([[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]])
print(tensor1)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [34]:
tensor2 = torch.tensor([[[9., 10.], [11., 12.]], [[13., 14.], [15., 16.]]])
print(tensor2)

tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]])


텐서의 사칙연산 수행하기

In [35]:
sum_tensor = tensor1 + tensor2
print(sum_tensor)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])


In [36]:
sub_tensor = tensor1 - tensor2
print(sub_tensor)

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])


In [37]:
mul_tensor = tensor1 * tensor2
print(mul_tensor)

tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])


In [38]:
div_tensor = tensor1 / tensor2
print(div_tensor)

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])


In [39]:
torch.add(tensor1, tensor2)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])

In [40]:
torch.sub(tensor1, tensor2)

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])

In [41]:
torch.mul(tensor1, tensor2)

tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])

In [42]:
torch.div(tensor1, tensor2)

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])

In [43]:
torch.matmul(tensor1, tensor2)

tensor([[[ 31.,  34.],
         [ 71.,  78.]],

        [[155., 166.],
         [211., 226.]]])

### 4.2 Autograd
파이토치에서는 Back Propagation을 이용해 파라미터를 업데이트하는 방법을 Autograd 방식으로 쉽게 구현할 수 있음.  
정말 간단한 딥러닝 모델을 설계하고 방정식 내에 존재하는 파라미터를 어떻게 업데이트할 수 있는지 알아보자.

In [44]:
if torch.cuda.is_available() :
    DEVICE = torch.device('cuda')
else :
    DEVICE = torch.device('cpu')

/home/nyongja/anaconda3/envs/pytorch_study/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448224956/work/c10/cuda/CUDAFunctions.cpp:115.)
  return torch._C._cuda_getDeviceCount() > 0


In [45]:
BATCH_SIZE = 64
INPUT_SIZE = 1000   
HIDDEN_SIZE = 100
OUTPUT_SIZE = 10

- BATCH_SIZE
파라미터 업데이트할 때 계산되는 데이터 개수  
BATCH_SIZE 수만큼 데이터를 이용해 Output 계산하고, BATCH_SIZE 수만큼 출력된 결괏값에 대한 오찻값 계산.  
Batch size 수만큼 계산된 오찻값을 평균해 back propagation을 적용하고 이를 바탕으로 파라미터 업데이트.  
이 예제에서 사용하는 batch size는 64이며, input으로 이용되는 데이터가 64개라는 것을 의미.  


- INPUT_SIZE
Input의 크기이자 입력층의 노드 수를 의미.  
즉, batch size가 64이며 input이 1000이라는 것은 1000 크기의 벡터 값을 64개 이용한다는 의미. (64, 1000)


- HIDDEN_SIZE
딥러닝 모델에서 Input을 다수의 파라미터를 이용해 계산한 결과에 한 번 더 계산되는 파라미터 수를 의미.  
즉, 입력층에서 은닉층으로 전달됐을 때 은닉층의 노드 수를 의미.  
(64, 1000)의 input들이 (1000, 100) 크기의 행렬과 행렬 곱을 계산하기 위해 설정한 수.  


- OUTPUT_SIZE
최종으로 출력되는 값의 벡터의 크기를 의미함.  
보통 output의 크기는 최종으로 비교하고자 하는 레이블의 크기와 동일하게 설정함.  
예를 들어 10개로 분류하려면 크기가 10짜리의 one-hot encoding을 이용하기 때문에 output의 크기를 10으로 맞추기도 하고 5 크기의 벡터 값에 대해 mean squared error를 계산하기 위해 output의 크기를 '5'로 맞추기도 함. 

In [46]:
x = torch.randn(BATCH_SIZE,
               INPUT_SIZE,
               device = DEVICE,
               dtype = torch.float,
               requires_grad = False)    # (1)
y = torch.randn(BATCH_SIZE,
               OUTPUT_SIZE,
               device = DEVICE,
               dtype = torch.float,
               requires_grad =  False)    # (2)
w1 = torch.randn(INPUT_SIZE,
                HIDDEN_SIZE,
                device = DEVICE,
                dtype = torch.float,
                requires_grad = True)    # (3)
w2 = torch.randn(HIDDEN_SIZE,
                 OUTPUT_SIZE,
                 device = DEVICE,
                 dtype = torch.float,
                 requires_grad = True)    # (4)

(1) randn은 평균이 0, 표준편차가 1인 정규분포에서 샘플링한 값으로, 데이터를 만든다는 것을 의미하며 데이터를 만들어 낼 때 데이터의 모양을 설정할 수 있음. 즉, 크기가 1,000짜리의 벡터를 64개 만들기 위해 BATCH_SIZE는 '64', INPUT_SIZE는 '1,000'으로 설정했으며 x는 (64, 1000) 모양의 데이터가 생성됨. 또한 해당 데이터는 input으로 이용되기 때문에 gradient를 계산할 필요가 없음. (gradient는 파라미터 값을 업데이트하기 위해 계산하는 것이므로)  

(2) Output도 input을 설정하는 것과 동일. batch size만큼 값이 필요하며 output과의 오차를 계산하기 위해 output의 크기를 10으로 설정  

(3) w1은 input의 데이터 크기가 1000이며 이와 행렬 곱을 하기 위해 다음 행의 값이 1000이어야 함.  또한 행렬 곱을 이용해 100 크기의 데이터를 생헝하기 위해 (1000, 100) 크기의 데이터를 생성함. input, outpu과 달리 gradient를 계산할 수 있도록 설정.  

(4) w2는 w1과 x를 행렬 곱한 결과에 계산할 수 있는 데이터여야 함.  w1과 x의 행렬 곱을 한 결과는 (64, 100)이며 (100, 10) 행렬을 통해 output을 계산할 수 있도록 모양 설정. gradient 계산할 수 있도록 설정.

In [54]:
learning_rate = 1e-6                                              # (1)
for t in range(1, 501) :                                          # (2)
    y_pred = x.mm(w1).clamp(min = 0).mm(w2)                       # (3)
    
    loss = (y_pred - y).pow(2).sum()                              # (4)
    if t % 100 == 0 :
        print("Iteration : ", t, "\t", "Loss : ", loss.item())    # (5)
    loss.backward()                                               # (6)
    
    with torch.no_grad() :                                        # (7)
        w1 -= learning_rate * w1.grad                             # (8)
        w2 -= learning_rate * w2.grad                             # (9)
        
        w1.grad.zero_()                                           # (10)
        w2.grad.zero_()                                           # (11)

Iteration :  100 	 Loss :  4.895027359452797e-06
Iteration :  200 	 Loss :  4.1376561057404615e-06
Iteration :  300 	 Loss :  3.596270744310459e-06
Iteration :  400 	 Loss :  3.1195650080917403e-06
Iteration :  500 	 Loss :  2.798250989144435e-06


(1) 파라미터 업데이트 시, gradient를 계산한 결과값에 1보다 작은 값을 곱해 업데이트.  

(2) 500번 반복해 파라미터 값을 업데이트하기 위해 반복문 설정.  

(3) 딥러닝 모델의 input인 x와 파라미터 w1 간의 행렬 곱을 이용해 나온 결괏값 계산. 그 이후 torch 모듈 내 clamp라는 메서드를 이용해 비선형 함수 적용. 딥러닝 모델에서는 층과 층 사이에 비선형 함수를 이용해 높은 표현력을 지니는 방정식을 얻을 수 있음. (ReLU()와 같은 역할!) clamp를 이용해 계산된 결과와 w2를 이용해 행렬 곱을 한 번 더 계산. 행렬 곱을 한 결과는 딥러닝 모델에서의 output을 의미하며 이는 예측값이므로 y_pred로 지정.  

(4) 예측값과 실제 레이블 값을 비교해 오차를 계산한 값을 loss라고 함. y_pred와 실제 레이블을 의미하는 y간의 차잇값을 계산한 후 pow함수로 제곱 취한 후 sum()으로 제곱차의 합 구함.  

(5) 반복 횟수를 의미하는 t가 100으로 나누어 떨어질때, 현재 진행 중인 반복문 횟수와 loss 값 출력해서 진행 과정 모니터링.  

(6) 계산된 loss 값에 대해 backward()메서드를 이용하면 각 파라미터 값에 대해 gradient를 계산하고 이를 통해 back propagation을 진행 함.  

(7) 각 파라미터 값에 대해 gradient를 계산한 결과를 이용해 파라미터 값을 업데이트 할 때는 해당 시점의 gradient 값을 고정한 후 업데이트를 진행함.  
(8) gradient 값을 고정한 상태에서 w1의 gradient값을 의미하는 w1.grad에 (1)에서 설장한 learning_rate 값을 곱한 결괏값을 기존 w1에서 빼줌. 음수를 이요하는 이유는 loss 값이 최소로 계산될 수 있는 파라미터 값을 찾기 위해 gradient 값에 대한 반대 방향으로 계산한다는 것을 의미.  

(9) (8)과 마찬가지로 w2에 대해서 진행

(10), (11) (8), (9)를 통해 각 파라미터 값을 업데이트 했다면 각 파라미터 값의 gradient를 초기화해 다음 반복문을 진행할 수 있도록 gradient 값을 0으로 설정. w1, w2 각각에 대해 동일하게 grad.zero_() 메서드를 적용해 gradient 값을 0으로 설정. 다음 back_propagation을 진행할 때 gradient값을 loss.backward()을 통해 새로 계산하기 때문.